namespace AO.Common
{
    public enum EquipSlot
    {
        Weap_Hud1 = 0x01,
        Weap_Hud2 = 0x0F,
        Weap_Hud3 = 0x02,
        Weap_Utils1 = 0x03,
        Weap_Utils2 = 0x04,
        Weap_Utils3 = 0x05,
        Weap_RightHand = 0x06,
        Weap_Belt = 0x07,
        Weap_LeftHand = 0x08,
        Weap_Deck1 = 0x09,
        Weap_Deck2 = 0x0A,
        Weap_Deck3 = 0x0B,
        Weap_Deck4 = 0x0C,
        Weap_Deck5 = 0x0D,
        Weap_Deck6 = 0x0E,
        Cloth_Neck = 0x11,
        Cloth_Head = 0x12,
        Cloth_Back = 0x13,
        Cloth_RightShoulder = 0x14,
        Cloth_Body = 0x15,
        Cloth_LeftShoulder = 0x16,
        Cloth_RightArm = 0x17,
        Cloth_Hands = 0x18,
        Cloth_LeftArm = 0x19,
        Cloth_RightWrist = 0x1A,
        Cloth_Legs = 0x1B,
        Cloth_LeftWrist = 0x1C,
        Cloth_RightFinger = 0x1D,
        Cloth_Feet = 0x1E,
        Cloth_LeftFinger = 0x1F,
        Imp_Eye = 0x21,
        Imp_Head = 0x22,
        Imp_Ear = 0x23,
        Imp_RightArm = 0x24,
        Imp_Body = 0x25,
        Imp_LeftArm = 0x26,
        Imp_RightWrist = 0x27,
        Imp_Waist = 0x28,
        Imp_LeftWrist = 0x29,
        Imp_RightHand = 0x2A,
        Imp_Legs = 0x2B,
        Imp_LeftHand = 0x2C,
        Imp_Feet = 0x2D
    }
}
