namespace AO.Common
{
    public enum MoveType
    {
        Forward_Start = 0x01,
        Forward_Stop = 0x02,
        Backward_Start = 0x03,
        Backward_Stop = 0x04,
        Strafe_Right_Start = 0x05,
        Strafe_Right_Stop = 0x06,
        Strafe_Left_Start = 0x07,
        Strafe_Left_Stop = 0x08,
        Turn_Right_Start = 0x09,
        Turn_Right_Mouse = 0x0a,
        Turn_Right_Stop = 0x0b,
        Turn_Left_Start = 0x0c,
        Turn_Left_Mouse = 0x0d,
        Turn_Left_Stop = 0x0e,
        Jump_Start = 0x0f,
        Jump_Stop = 0x10,
        Elevate_Up_Start = 0x11,
        Elevate_Up_Stop = 0x12,
        Unknown0x13 = 0x13,
        Unknown0x14 = 0x14,
        Full_Stop = 0x15,
        Unknown0x16 = 0x16,
        Switch_To_Frozen = 0x17,
        Switch_To_Walk = 0x18,
        Switch_To_Run = 0x19,
        Switch_To_Swim = 0x1a,
        Switch_To_Crawl = 0x1b,
        Switch_To_Sneak = 0x1c,
        Switch_To_Fly = 0x1d,
        Switch_To_Sit = 0x1e,
        Unknown0x1f = 0x1f,
        Unknown0x20 = 0x20,
        Switch_To_Sleep = 0x21,
        Switch_To_Lounge = 0x22,
        Leave_Swim = 0x23,
        Leave_Sneak = 0x24,
        Leave_Sit = 0x25,
        Leave_Frozen = 0x26,
        Leave_Fly = 0x27,
        Leave_Crawl = 0x28,
        Leave_Sleep = 0x29,
        Leave_Lounge = 0x2a
    }
}